# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c32ca3c6cdf9bc1a349663af0ff3b0558f9caf7d82dd73dba55903d7b1cfea67b2cc2e3906ea7efe61c3e74297a581fe2f309c0cd50d7cd43c0f57a07693838

test:
  secret_key_base: 4750e030ec156daf3e81c54d3ed458f59e0458e1bc9a14d8df05cd86c3e9b299e846fa952ecc78e8f6c6463e59003f446fc0dc23a99047db6b71bd94a2556713

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
